/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/appointment/AppointmentFormPage': RouteRecordInfo<'/appointment/AppointmentFormPage', '/appointment/AppointmentFormPage', Record<never, never>, Record<never, never>>,
    '/appointment/AppointmentListPage': RouteRecordInfo<'/appointment/AppointmentListPage', '/appointment/AppointmentListPage', Record<never, never>, Record<never, never>>,
    '/dashboard/DashboardPage': RouteRecordInfo<'/dashboard/DashboardPage', '/dashboard/DashboardPage', Record<never, never>, Record<never, never>>,
    '/doctor/DoctorFormPage': RouteRecordInfo<'/doctor/DoctorFormPage', '/doctor/DoctorFormPage', Record<never, never>, Record<never, never>>,
    '/doctor/DoctorListPage': RouteRecordInfo<'/doctor/DoctorListPage', '/doctor/DoctorListPage', Record<never, never>, Record<never, never>>,
    '/patient/PatientFormPage': RouteRecordInfo<'/patient/PatientFormPage', '/patient/PatientFormPage', Record<never, never>, Record<never, never>>,
    '/patient/PatientListPage': RouteRecordInfo<'/patient/PatientListPage', '/patient/PatientListPage', Record<never, never>, Record<never, never>>,
    '/specialty/SpecialtyFormPage': RouteRecordInfo<'/specialty/SpecialtyFormPage', '/specialty/SpecialtyFormPage', Record<never, never>, Record<never, never>>,
    '/specialty/SpecialtyListPage': RouteRecordInfo<'/specialty/SpecialtyListPage', '/specialty/SpecialtyListPage', Record<never, never>, Record<never, never>>,
    '/status/StatusFormPage': RouteRecordInfo<'/status/StatusFormPage', '/status/StatusFormPage', Record<never, never>, Record<never, never>>,
    '/status/StatusListPage': RouteRecordInfo<'/status/StatusListPage', '/status/StatusListPage', Record<never, never>, Record<never, never>>,
  }
}
